name: Project pipeline

on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and Push Docker Server image
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./server 
        file: ./server/dockerfile
        push: true
        tags: ctbama/server-ec2:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull server image from docker hub
        run: docker pull ctbama/server-ec2:latest
      - name: Delete old server container
        run: docker rm -f server-app-container || true
      - name: Run Docker server Container
        run: docker run -d -p 4040:4040 --name server-app-container -e DB_URL='${{ secrets.DB_URL }}' ctbama/server-ec2:latest
